=== Ryudo302/mychart/mychart/mychart-app/src/test/resources/datasets/mychart.dtd
<!ELEMENT dataset (
   (TB_ARTISTA|
    TB_ARTISTA_CANCAO|
    TB_CANCAO|
    TB_POSICAO|
    TB_TOP_MUSICAL|
    TB_TOP_MUSICAL_TB_POSICAO)*)>

<!ELEMENT TB_ARTISTA EMPTY>
<!ATTLIST TB_ARTISTA
    COD_ARTISTA CDATA #REQUIRED
    NOM_ARTISTA CDATA #REQUIRED
    DSC_TIPO CDATA #REQUIRED
>

<!ELEMENT TB_ARTISTA_CANCAO EMPTY>
<!ATTLIST TB_ARTISTA_CANCAO
    COD_ARTISTA CDATA #REQUIRED
    COD_CANCAO CDATA #REQUIRED
    NUM_ORDEM CDATA #REQUIRED
>

<!ELEMENT TB_CANCAO EMPTY>
<!ATTLIST TB_CANCAO
    COD_CANCAO CDATA #REQUIRED
    DSC_TITULO CDATA #REQUIRED
>

<!ELEMENT TB_POSICAO EMPTY>
<!ATTLIST TB_POSICAO
    COD_CANCAO CDATA #REQUIRED
    NUM_TOP_MUSICAL CDATA #REQUIRED
    NUM_MELHOR_POSICAO CDATA #REQUIRED
    NUM_POSICAO CDATA #REQUIRED
    NUM_PERMANENCIA_MELHOR_POSICAO CDATA #REQUIRED
    NUM_PERMANENCIA_TOTAL CDATA #REQUIRED
>

<!ELEMENT TB_TOP_MUSICAL EMPTY>
<!ATTLIST TB_TOP_MUSICAL
    NUM_TOP_MUSICAL CDATA #REQUIRED
    DTA_FINAL CDATA #IMPLIED
    DTA_INICIAL CDATA #REQUIRED
    NUM_PROXIMO_TOP_MUSICAL CDATA #IMPLIED
>

<!ELEMENT TB_TOP_MUSICAL_TB_POSICAO EMPTY>
<!ATTLIST TB_TOP_MUSICAL_TB_POSICAO
    TOPMUSICAL_NUM_TOP_MUSICAL CDATA #REQUIRED
    POSICOES_COD_CANCAO CDATA #REQUIRED
    POSICOES_NUM_TOP_MUSICAL CDATA #REQUIRED
    POSICOES_KEY CDATA #REQUIRED
>

=== Ryudo302/mychart/mychart/mychart-app/src/test/resources/datasets/cancoes-dataset.xml
<!DOCTYPE dataset SYSTEM "./mychart.dtd">
<dataset>
	<TB_ARTISTA COD_ARTISTA="1" DSC_TIPO="MASCULINO_SOLO" NOM_ARTISTA="Justin Timberlake" />
	<TB_ARTISTA COD_ARTISTA="2" DSC_TIPO="FEMININO_SOLO" NOM_ARTISTA="Rihanna" />

	<TB_CANCAO DSC_TITULO="Rehab" COD_CANCAO="1" />
	<TB_CANCAO DSC_TITULO="Unfaithful" COD_CANCAO="2" />

	<TB_ARTISTA_CANCAO COD_CANCAO="1" COD_ARTISTA="2" NUM_ORDEM="0" />
	<TB_ARTISTA_CANCAO COD_CANCAO="1" COD_ARTISTA="1" NUM_ORDEM="1" />
	<TB_ARTISTA_CANCAO COD_CANCAO="2" COD_ARTISTA="2" NUM_ORDEM="0" />
</dataset>

=== Ryudo302/mychart/mychart/mychart-app/src/test/resources/datasets/top-musical-dataset.xml
<!DOCTYPE dataset SYSTEM "./mychart.dtd">
<dataset>
	<TB_ARTISTA COD_ARTISTA="1" DSC_TIPO="MASCULINO_SOLO" NOM_ARTISTA="Justin Timberlake" />
	<TB_ARTISTA COD_ARTISTA="2" DSC_TIPO="FEMININO_SOLO" NOM_ARTISTA="Rihanna" />

	<TB_CANCAO DSC_TITULO="Rehab" COD_CANCAO="1" />
	<TB_CANCAO DSC_TITULO="Unfaithful" COD_CANCAO="2" />

	<TB_ARTISTA_CANCAO COD_CANCAO="1" COD_ARTISTA="2" NUM_ORDEM="0" />
	<TB_ARTISTA_CANCAO COD_CANCAO="1" COD_ARTISTA="1" NUM_ORDEM="1" />
	<TB_ARTISTA_CANCAO COD_CANCAO="2" COD_ARTISTA="2" NUM_ORDEM="0" />

	<TB_TOP_MUSICAL DTA_INICIAL="2015-01-08" NUM_TOP_MUSICAL="2" />
	<TB_TOP_MUSICAL DTA_INICIAL="2015-01-01" DTA_FINAL="2014-01-07" NUM_PROXIMO_TOP_MUSICAL="2" NUM_TOP_MUSICAL="1" />

	<!-- 
		1º Top 
		1 Rihanna feat. Justin Timberlake - "Rehab" [ NEW ] [1ª Semana] [PP:1]
		2 Rihanna - "Unfaithful" [ NEW ] [1ª Semana] [PP:2]
	-->

	<TB_POSICAO NUM_MELHOR_POSICAO="1" COD_CANCAO="1" NUM_PERMANENCIA_TOTAL="1" NUM_TOP_MUSICAL="1"
		NUM_PERMANENCIA_MELHOR_POSICAO="1" NUM_POSICAO="1" />
	<TB_POSICAO NUM_MELHOR_POSICAO="2" COD_CANCAO="2" NUM_PERMANENCIA_TOTAL="1" NUM_TOP_MUSICAL="1"
		NUM_PERMANENCIA_MELHOR_POSICAO="1" NUM_POSICAO="2" />

	<TB_TOP_MUSICAL_TB_POSICAO TOPMUSICAL_NUM_TOP_MUSICAL="1" POSICOES_NUM_TOP_MUSICAL="1"
		POSICOES_COD_CANCAO="1" POSICOES_KEY="1" />
	<TB_TOP_MUSICAL_TB_POSICAO TOPMUSICAL_NUM_TOP_MUSICAL="1" POSICOES_NUM_TOP_MUSICAL="1"
		POSICOES_COD_CANCAO="2" POSICOES_KEY="2" />

	<!-- 
		2º Top
		1 Rihanna - "Unfaithful" [ +1 ] [2ª Semana] [PP:1]
		2 Rihanna feat. Justin Timberlake - "Rehab" [ -1 ] [2ª Semana] [PP:1]
	-->

	<TB_POSICAO NUM_MELHOR_POSICAO="1" COD_CANCAO="2" NUM_PERMANENCIA_TOTAL="2" NUM_TOP_MUSICAL="2"
		NUM_PERMANENCIA_MELHOR_POSICAO="1" NUM_POSICAO="1" />
	<TB_POSICAO NUM_MELHOR_POSICAO="2" COD_CANCAO="1" NUM_PERMANENCIA_TOTAL="2" NUM_TOP_MUSICAL="2"
		NUM_PERMANENCIA_MELHOR_POSICAO="1" NUM_POSICAO="2" />

	<TB_TOP_MUSICAL_TB_POSICAO TOPMUSICAL_NUM_TOP_MUSICAL="2" POSICOES_NUM_TOP_MUSICAL="2"
		POSICOES_COD_CANCAO="2" POSICOES_KEY="1" />
	<TB_TOP_MUSICAL_TB_POSICAO TOPMUSICAL_NUM_TOP_MUSICAL="2" POSICOES_NUM_TOP_MUSICAL="2"
		POSICOES_COD_CANCAO="1" POSICOES_KEY="2" />
</dataset>
